version: 2
updates:
  # Maintain dependencies for terraform - gcp
  - package-ecosystem: "terraform"
    directory: "/terraform/gcp"
    schedule:
      interval: "weekly"
  # Maintain dependencies for terraform - azure
  - package-ecosystem: "terraform"
    directory: "/terraform/azure"
    schedule:
      interval: "weekly"
